/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gc.tiendaipc2.FRAME;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author james
 */
public class CargaArchivo extends javax.swing.JFrame {

    /**
     * Creates new form CargaArchivo
     */
    public CargaArchivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        BotonSeleccionar = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPane.setBackground(new java.awt.Color(179, 221, 185));

        BotonSeleccionar.setText("Seleccionar");
        BotonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSeleccionarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane.setViewportView(jTextArea1);

        jTextField.setBackground(new java.awt.Color(177, 177, 177));
        jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BotonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane)
                .addContainerGap())
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonSeleccionar)
                    .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSeleccionarActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
       
                //Creamos el objeto JFileChooser
                JFileChooser fc=new JFileChooser();
                
                //Creamos el filtro
                FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT", "txt");

                //Le indicamos el filtro
                fc.setFileFilter(filtro);

                //Abrimos la ventana, guardamos la opcion seleccionada por el empleado
                int seleccion=fc.showOpenDialog(contentPane);

                //Si el usuario, pincha en aceptar
                if(seleccion==JFileChooser.APPROVE_OPTION){

                    //Seleccionamos el fichero
                    File fichero=fc.getSelectedFile();

                    //Ecribe la ruta del fichero seleccionado en el campo de texto
                    jTextField.setText(fichero.getAbsolutePath());
                     
                    
                    
                    
                    try(FileReader fr=new FileReader(fichero)){
                                            
                        String cadena="";
                        int valor=fr.read();
                        while(valor!=-1){
                            cadena=cadena+(char)valor;
                            valor=fr.read();
                        }
                        jTextArea1.setText(cadena);
                                              
                        
                    } catch (IOException e1) {
                        e1.printStackTrace();
                    } 
                }
    }//GEN-LAST:event_BotonSeleccionarActionPerformed

    private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        
                String texto = jTextArea1.getText();
                String[] linea = texto.split("\n");
                AgregarDatos(linea);
                
    }//GEN-LAST:event_AceptarActionPerformed
    
    //METODO QUE DETERMINA QUE TIPO DE INFORMACION LEE
    public void AgregarDatos(String [] linea){
        
        for(int i=0;i<linea.length;i++){
            
            String texto=linea[i];
            //las palabras separadas por coma las guarda en arreglo de palabras  
            String[] TipoLinea = texto.split(",");
            


                if(TipoLinea[0].equalsIgnoreCase("TIENDA")){
                    String nombre=TipoLinea[1];
                    String direccion=TipoLinea[2];
                    String codT=TipoLinea[3];
                    String tel1=TipoLinea[4];
                    System.out.println(nombre);
                }
                if(TipoLinea[0].equalsIgnoreCase("TIEMPO")){
                    String nombre=TipoLinea[1];
                    String direccion=TipoLinea[2];
                    String codT=TipoLinea[3];

                }
                if(TipoLinea[0].equalsIgnoreCase("PRODUCTO")){
                    String nombre=TipoLinea[1];
                    String direccion=TipoLinea[2];
                    String codT=TipoLinea[3];

                }
                if(TipoLinea[0].equalsIgnoreCase("EMPLEADO")){
                    String nombre=TipoLinea[1];
                    String direccion=TipoLinea[2];
                    String codT=TipoLinea[3];

                }
                if(TipoLinea[0].equalsIgnoreCase("CLIENTE")){
                    String nombre=TipoLinea[1];
                    String direccion=TipoLinea[2];
                    String codT=TipoLinea[3];

                }
                if(TipoLinea[0].equalsIgnoreCase("PEDIDO")){
                    String nombre=TipoLinea[1];
                    String direccion=TipoLinea[2];
                    String codT=TipoLinea[3];

                }
                
                
            
            
        }
        
        

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton BotonSeleccionar;
    private javax.swing.JPanel contentPane;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
