
package gc.tiendaipc2.FRAME.NuevaInformacion;

import static ConexionMySQL.Conexion.getConnection;
import static gc.tiendaipc2.FRAME.NuevaInformacion.CargaArchivo.AgregaProducto;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author james
 */
public class AgregaProducto extends javax.swing.JFrame {
    ArrayList<String> ArrayCodPro = new ArrayList<>();
    String cod,CODIGOTIENDA,preciot;
    
    /**
     * Creates new form AgregaProducto
     * @param CODIGOTIENDA
     */
    public AgregaProducto(String CODIGOTIENDA) {
        initComponents();
        this.CODIGOTIENDA=CODIGOTIENDA;
        tienda.setText(CODIGOTIENDA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Garantia = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tienda = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        fabricante = new javax.swing.JTextField();
        cantidadJ = new javax.swing.JTextField();
        Descripcion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        codigoJ = new javax.swing.JTextField();
        GarantiaSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Garantia.setBackground(new java.awt.Color(53, 192, 124));
        Garantia.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Phetsarath OT", 0, 24)); // NOI18N
        jLabel1.setText("Agrega un nuevo producto ");
        Garantia.add(jLabel1);
        jLabel1.setBounds(190, 20, 328, 42);

        jButton1.setBackground(new java.awt.Color(208, 48, 52));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Garantia.add(jButton1);
        jButton1.setBounds(20, 10, 98, 40);

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Garantia.add(jButton2);
        jButton2.setBounds(300, 430, 122, 37);

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Garantia.add(jButton3);
        jButton3.setBounds(180, 430, 105, 37);

        jLabel2.setText("Estas en la tienda:");
        Garantia.add(jLabel2);
        jLabel2.setBounds(12, 87, 181, 18);

        tienda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Garantia.add(tienda);
        tienda.setBounds(210, 80, 210, 30);

        jLabel4.setText("Nombre:");
        Garantia.add(jLabel4);
        jLabel4.setBounds(10, 120, 163, 31);

        jLabel5.setText("Fabricante:");
        Garantia.add(jLabel5);
        jLabel5.setBounds(12, 160, 163, 31);

        jLabel6.setText("Codigo de producto:");
        Garantia.add(jLabel6);
        jLabel6.setBounds(10, 200, 163, 31);

        jLabel7.setText("Cantidad");
        Garantia.add(jLabel7);
        jLabel7.setBounds(10, 240, 163, 31);

        jLabel8.setText("Descripcion:");
        Garantia.add(jLabel8);
        jLabel8.setBounds(10, 320, 163, 31);

        jLabel9.setText("Garantia (meses)");
        Garantia.add(jLabel9);
        jLabel9.setBounds(10, 360, 163, 31);
        Garantia.add(nombre);
        nombre.setBounds(210, 120, 209, 31);
        Garantia.add(fabricante);
        fabricante.setBounds(210, 160, 209, 31);
        Garantia.add(cantidadJ);
        cantidadJ.setBounds(210, 240, 209, 31);

        Descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripcionActionPerformed(evt);
            }
        });
        Garantia.add(Descripcion);
        Descripcion.setBounds(210, 320, 209, 31);

        jLabel11.setText("*");
        Garantia.add(jLabel11);
        jLabel11.setBounds(180, 120, 20, 20);

        jLabel12.setText("*");
        Garantia.add(jLabel12);
        jLabel12.setBounds(180, 160, 20, 20);

        jLabel13.setText("*");
        Garantia.add(jLabel13);
        jLabel13.setBounds(180, 200, 20, 20);
        Garantia.add(precio);
        precio.setBounds(210, 280, 209, 31);

        jLabel14.setText("*");
        Garantia.add(jLabel14);
        jLabel14.setBounds(180, 240, 20, 20);

        jLabel15.setText("*");
        Garantia.add(jLabel15);
        jLabel15.setBounds(180, 280, 20, 20);

        jLabel16.setText("Precio:");
        Garantia.add(jLabel16);
        jLabel16.setBounds(10, 280, 163, 31);
        Garantia.add(codigoJ);
        codigoJ.setBounds(210, 200, 209, 31);

        GarantiaSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Garantia.add(GarantiaSpinner);
        GarantiaSpinner.setBounds(210, 370, 210, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Garantia, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Garantia, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        preciot=precio.getText();
        obtenerDatos();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        tienda.setText("");
        nombre.setText("");
        fabricante.setText("");
        codigoJ.setText("");
        Descripcion.setText("");
        cantidadJ.setText("");
        GarantiaSpinner.setValue(0);
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Descripcion;
    private javax.swing.JPanel Garantia;
    private javax.swing.JSpinner GarantiaSpinner;
    private javax.swing.JTextField cantidadJ;
    private javax.swing.JTextField codigoJ;
    private javax.swing.JTextField fabricante;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    private javax.swing.JLabel tienda;
    // End of variables declaration//GEN-END:variables
    /**
     * Metodo que obtiene los datos de las cajas de texto
     */
    private void obtenerDatos() {
        
        if(nombre.getText().length()>1&&fabricante.getText().length()>1&&
                codigoJ.getText().length()>1){
            comprobarDuplicado();
        }else{
            JOptionPane.showMessageDialog(null,"Ingresa los campos obligatorios que tengan *");
        }
       
    }
    /**
     * comprueba que el codigo de producto que no s repita
     */
    private void comprobarDuplicado() {
         
        String query = "SELECT * FROM productos";

        try (PreparedStatement preSt = getConnection().prepareStatement(query);
                ResultSet result = preSt.executeQuery()) {

            //obtiene el codigo de los productos
            while (result.next()) {
                
                cod=result.getString(1);
                
                
                ArrayCodPro.add(cod);
                
            }

            result.close();
            
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
        
        if(!ArrayCodPro.contains(codigoJ.getText()) ){
            agregaNuevoProducto();
        }
        else{
            JOptionPane.showMessageDialog(null, "el codigo que has ingresado para el nuevo producto \n"
                    + "ya existe. puedes utilizar  la opcion Nueva existencia\n"
                    + "Por favor utiliza otro codigo.");
        }    
    }
    
        /**
         * Agrega el nuevo producto a la Base de Datos
         */
    
        private void agregaNuevoProducto() {
            
        try{
            String tda=tienda.getText();
            String nom=nombre.getText();
            String fab=fabricante.getText();
            String codpro=codigoJ.getText();
            String des=Descripcion.getText();
            int Cant = Integer.parseInt(cantidadJ.getText());
            double Precio = Double.parseDouble(preciot);
            //int garantia = Integer.parseInt(garantiaJ.getText());
            int garantia= (Integer) GarantiaSpinner.getValue();
            
           
            
            //llama al metodo para agregar productos
            AgregaProducto(codpro,nom,fab,Cant, Precio, tda,des, garantia);
            JOptionPane.showMessageDialog(null,"Se agregado el nuevo producto a la tienda");
        
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Debes ingresar solo numeros en \n"
                    + "los campos requeridos ");
        
        }
    }

    
}
