/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gc.tiendaipc2.FRAME.NuevaInformacion;

import static ConexionMySQL.Conexion.getConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author james
 */
public class tiempoTiendas extends javax.swing.JFrame {
    
    ArrayList<String> ArrayOrigen = new ArrayList<>();
    ArrayList<String> ArrayDestino = new ArrayList<>();
    ArrayList<Integer> ArrayDias = new ArrayList<>();
    ArrayList<String> Arraycod = new ArrayList<>();
    ArrayList<String> Arraynom = new ArrayList<>();
    ArrayList<String> Arraydir = new ArrayList<>();
    PreparedStatement ps;
    int dias;
    /**
     * Creates new form tiempoTiendas
     */
    public tiempoTiendas() {
        
        initComponents();
        obtenerTiempoTiendas();
        obtenerTiendas();
        muestratiendaJCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Tienda1 = new javax.swing.JComboBox<>();
        Tienda2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mostrar_Tiempo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(72, 173, 155));

        jLabel1.setFont(new java.awt.Font("Ubuntu Condensed", 2, 24)); // NOI18N
        jLabel1.setText("ACTUALIZA Tiempo --entre-- Tiendas");

        jButton2.setText("Actualizar tiempo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Tienda1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        Tienda1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una tienda" }));

        Tienda2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        Tienda2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una tienda" }));

        jLabel2.setText("Tienda 2");

        jLabel3.setText("Tienda 1");

        jLabel5.setText("Nuevo tiempo estimado (dias);");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 31, 1));

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Mostrar_Tiempo.setColumns(20);
        Mostrar_Tiempo.setRows(5);
        jScrollPane1.setViewportView(Mostrar_Tiempo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Tienda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(87, 87, 87)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Tienda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tienda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tienda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //obtiene los datos ingresados a la caja de texto y 
        //los datos seleccionados con Jcombobox.
        dias = (Integer) jSpinner1.getValue();
        String origenq = (String) Tienda1.getSelectedItem();
        String destinoq = (String) Tienda2.getSelectedItem();
        int dias_esperaq=dias;
        //
        obtieneCod(origenq,destinoq,dias_esperaq);
        Mostrar_Tiempo.setText("");
        ListadoTiempo();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Mostrar_Tiempo;
    private javax.swing.JComboBox<String> Tienda1;
    private javax.swing.JComboBox<String> Tienda2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
    private void obtieneCod(String origenq,String destinoq,int dias_espera){
        String[] org=origenq.split(",");
        String[] des=destinoq.split(",");
        
        if(org[0].equalsIgnoreCase(des[0])){
            JOptionPane.showInternalMessageDialog(null, "No puedes programar dias de entrega \n "
                    + "para la misma tienda.\nSelecciona otra...");
        }else{
            
        
        
            if( ArrayOrigen.contains(org[0])&&ArrayDestino.contains(des[0])){

                actualizarDias(org[0],des[0],dias_espera);
            }
            else if(ArrayDestino.contains(org[0])&&ArrayOrigen.contains(des[0])){
                actualizarDias(des[0],org[0],dias_espera);
            }
        }
        
    }
    /**
     * Obtien los datos de la tabla de tiempo
     */
    private void obtenerTiempoTiendas() {
        
        String query = "SELECT * FROM tiempo_entre_tiendas";

        try (PreparedStatement preSt = getConnection().prepareStatement(query);
                ResultSet result = preSt.executeQuery()) {
            //obtiene los datos de la tabla de tiempo 
            while (result.next()) {
              
                String origen=result.getString(1);
                String destino=result.getString(2);
                int diass=result.getInt(3);
                //introduce los datos en un Array para mostrarlos
                // posteriormente en un JComoboBox y TextField
                ArrayOrigen.add(origen);
                ArrayDestino.add(destino);
                ArrayDias.add(diass);
                
            }
            
            result.close();
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    private void obtenerTiendas() {
        
        String query = "SELECT * FROM tienda";

        try (PreparedStatement preSt = getConnection().prepareStatement(query);
                ResultSet result = preSt.executeQuery()) {
            //obtiene los datos de la tabla de tiempo 
            while (result.next()) {
              
                String cod=result.getString(1);
                String nom=result.getString(2);
                String dir=result.getString(2);
                

                Arraycod.add(cod);
                Arraynom.add(nom);
                Arraydir.add(dir);
                
            }
            
            result.close();
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    public void muestratiendaJCombo(){
  
        for(int j=0;j<Arraycod.size();j++){           
            Tienda1.addItem(Arraycod.get(j)+", "+Arraynom.get(j));  
            Tienda2.addItem(Arraycod.get(j)+", "+Arraynom.get(j));
        }
 
    }
    
     /**
     * actualiza los dias para un pedido de una tienda a otra
     *
     * @param origen1
     * @param destino1
     * @param dias1
     */
    public void actualizarDias(String origen1,String destino1,int dias1) {

        String query = "UPDATE tiempo_entre_tiendas SET dias_espera = ? WHERE origen = ? AND destino= ?";

        try (PreparedStatement preSt = getConnection().prepareStatement(query)) {

            preSt.setInt(1, dias1);
            preSt.setString(2, origen1);
            preSt.setString(3, destino1);

            preSt.executeUpdate();

            JOptionPane.showMessageDialog(null, "TIEMPO ACTUALIZADO");

            preSt.close();
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
        
       
    }

    private void ListadoTiempo() {
        
        
        
        
        
        
        String query = "SELECT * FROM tiempo_entre_tiendas";

        try (PreparedStatement preSt = getConnection().prepareStatement(query);
                ResultSet result = preSt.executeQuery()) {

            
            while (result.next()) {
                
                Mostrar_Tiempo.append("||  "+result.getString(1)+"|   "+result.getString(2)+"|   "+result.getString(3)+"||\n");
                
            }

            result.close();
            
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
        
        

    
        
        
        
        
        
    }



}
